# Generated by Django 4.1.2 on 2022-12-22 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Company_Task',
        ),
    ]
